name: Install ConformU
author: conformu-install
description: Install ConformU platform on Linux, Windows, and macOS
branding:
  icon: download
  color: blue

inputs:
  version:
    description: "ConformU version to install (default: latest)"
    required: false
    default: latest
  cache:
    description: "Enable caching of downloaded files"
    required: false
    default: 'true'

outputs:
  version:
    description: Installed ConformU version
    value: ${{ inputs.version == 'latest' && steps.get-version.outputs.release || inputs.version }}

runs:
  using: composite
  steps:
    - id: get-version
      if: inputs.version == 'latest'
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ASCOMInitiative/ConformU
        token: ${{ github.token }}

    - id: cache-restore
      if: inputs.cache == 'true'
      uses: actions/cache/restore@v5
      with:
        key: conformu-${{ inputs.version == 'latest' && steps.get-version.outputs.release || inputs.version }}-${{ runner.os }}
        restore-keys: |
          conformu-${{ inputs.version == 'latest' && steps.get-version.outputs.release || inputs.version }}-
          conformu-
        path: |
          conformu.linux-x64.tar.xz
          ConformU.*.Setup.exe
          ConformU-Installer.dmg

    - id: install-linux
      if: runner.os == 'Linux'
      run: |
        VERSION="${{ inputs.version == 'latest' && steps.get-version.outputs.release || inputs.version }}"
        if [ ! -f "conformu.linux-x64.tar.xz" ]; then
          wget -q --header="Authorization: Bearer ${{ github.token }}" "https://github.com/ASCOMInitiative/ConformU/releases/download/$VERSION/conformu.linux-x64.tar.xz"
        else
          echo "Using cached conformu.linux-x64.tar.xz"
        fi
        tar -xf conformu.linux-x64.tar.xz
        chmod +x conformu
        echo "$PWD" >> $GITHUB_PATH
      shell: bash

    - id: install-windows
      if: runner.os == 'Windows'
      run: |
        $release = "${{ inputs.version == 'latest' && steps.get-version.outputs.release || inputs.version }}"
        $headers = @{ Authorization = "Bearer ${{ github.token }}" }
        $releaseInfo = Invoke-RestMethod "https://api.github.com/repos/ASCOMInitiative/ConformU/releases/tags/$release" -Headers $headers
        $asset = $releaseInfo.assets | Where-Object { $_.name -like "ConformU.*.Setup.exe" }
        $installer = $asset.name
        if (-not (Test-Path $installer)) {
          Invoke-WebRequest $asset.browser_download_url -OutFile $installer -UseBasicParsing
        } else {
          Write-Host "Using cached $installer"
        }
        Start-Process $installer -ArgumentList "/SP", "/VERYSILENT" -Wait -NoNewWindow
        echo "${env:ProgramFiles}\ASCOM\ConformU" >> $env:GITHUB_PATH
      shell: powershell

    - id: install-macos
      if: runner.os == 'macOS'
      run: |
        $release = "${{ inputs.version == 'latest' && steps.get-version.outputs.release || inputs.version }}"
        $headers = @{ Authorization = "Bearer ${{ github.token }}" }
        $releaseInfo = Invoke-RestMethod "https://api.github.com/repos/ASCOMInitiative/ConformU/releases/tags/$release" -Headers $headers
        $asset = $releaseInfo.assets | Where-Object { $_.name -eq "ConformU-Installer.dmg" }
        $installer = $asset.name
        if (-not (Test-Path $installer)) {
          Invoke-WebRequest $asset.browser_download_url -OutFile $installer -UseBasicParsing
        } else {
          Write-Host "Using cached $installer"
        }
        hdiutil attach $installer
        cp -R "/Volumes/ConformU-Installer/ConformU.app" /Applications/
        hdiutil detach "/Volumes/ConformU-Installer"
        echo "/Applications/ConformU.app/Contents/Resources" >> $env:GITHUB_PATH
      shell: pwsh

    - id: cache-save
      if: inputs.cache == 'true' && steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        key: conformu-${{ inputs.version == 'latest' && steps.get-version.outputs.release || inputs.version }}-${{ runner.os }}
        path: |
          conformu.linux-x64.tar.xz
          ConformU.*.Setup.exe
          ConformU-Installer.dmg
